test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
qa:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
homologation:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>